# Generated by Django 5.2.17 on 2026-09-28 13:05
#
# PLACEHOLDER migration for ham/requests/models.py's placeholder model — see that file's
# module docstring. Orchestrator: drop this migration (and the model) when merging S2.2's
# real ham/requests app; re-point ham/media/migrations/0001_initial.py's dependency at
# whichever S2.2 migration actually creates AssistanceRequest.

from django.db import migrations, models

import ham.platform.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssistanceRequest",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEEDS_PHONE_CHECK", "NEEDS_PHONE_CHECK"),
                            ("SUBMITTED", "SUBMITTED"),
                            ("AWAITING_APPROVAL", "AWAITING_APPROVAL"),
                            ("CANCELLED", "CANCELLED"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("RECONSIDERATION_PENDING", "RECONSIDERATION_PENDING"),
                        ],
                        default="SUBMITTED",
                        max_length=32,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "requests_assistance_request",
            },
        ),
    ]
