# Generated by Django 5.2.17 on 2026-09-28 13:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import ham.platform.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # intake.md §3: "reference_number (int, unique, from a Postgres sequence; shown as
        # 'HAM #047')" -- ham.requests.models.next_reference_number() calls nextval() on this
        # sequence explicitly (the model field itself carries no DEFAULT, since the value must
        # be known before the row is built, inside the same @command transaction).
        migrations.RunSQL(
            "CREATE SEQUENCE requests_reference_number_seq START 1;",
            "DROP SEQUENCE requests_reference_number_seq;",
        ),
        migrations.CreateModel(
            name="AssistanceRequest",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.PositiveIntegerField(editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEEDS_PHONE_CHECK", "NEEDS_PHONE_CHECK"),
                            ("SUBMITTED", "SUBMITTED"),
                            ("AWAITING_APPROVAL", "AWAITING_APPROVAL"),
                            ("CANCELLED", "CANCELLED"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("RECONSIDERATION_PENDING", "RECONSIDERATION_PENDING"),
                        ],
                        default="SUBMITTED",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("public_form", "Public form"),
                            ("church_link", "Church-issued link"),
                            ("assisted", "Entered on someone's behalf"),
                        ],
                        default="public_form",
                        max_length=16,
                    ),
                ),
                ("intake_source_id", models.UUIDField(blank=True, null=True)),
                ("created_by_user_id", models.UUIDField(blank=True, null=True)),
                (
                    "need_category",
                    models.CharField(
                        choices=[
                            ("plumbing", "Plumbing"),
                            ("electrical", "Electrical"),
                            ("roof", "Roof"),
                            ("carpentry", "Carpentry & repairs"),
                            ("accessibility", "Accessibility"),
                            ("painting", "Painting"),
                            ("yard_outdoor", "Yard & outdoor"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("urgent_requested", models.BooleanField(default=False)),
                ("urgency_justification", models.TextField(blank=True, default="")),
                (
                    "urgency_status",
                    models.CharField(
                        choices=[
                            ("none", "none"),
                            ("awaiting_certification", "awaiting_certification"),
                            ("certified", "certified"),
                            ("not_certified", "not_certified"),
                        ],
                        default="none",
                        max_length=24,
                    ),
                ),
                ("known_hazards", models.TextField(blank=True, default="")),
                ("preferred_availability", models.TextField(blank=True, default="")),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone_call", "Phone call"),
                            ("text_message", "Text message"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "relationship_to_property",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("authorized_family_member", "Authorized family member"),
                            ("tenant", "Tenant"),
                        ],
                        max_length=32,
                    ),
                ),
                ("attestation_version", models.CharField(max_length=32)),
                (
                    "attested_statements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        default=list,
                        size=None,
                    ),
                ),
                ("attested_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField()),
                ("status_changed_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requester_access_ends_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "cancel_reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spam", "spam"),
                            ("requester_withdrew", "requester_withdrew"),
                            ("duplicate_submission", "duplicate_submission"),
                            ("couldnt_reach_them", "couldnt_reach_them"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("cancel_note", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "requests_request",
            },
        ),
        migrations.CreateModel(
            name="RequestContactVerification",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone")], max_length=8
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("email_code", "email_code"),
                            ("email_link", "email_link"),
                            ("staff_phone_call", "staff_phone_call"),
                        ],
                        max_length=24,
                    ),
                ),
                ("value_key", models.CharField(max_length=64)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("intake", "Intake"),
                            ("link_regeneration", "Link regeneration"),
                        ],
                        default="intake",
                        max_length=24,
                    ),
                ),
                ("verified_at", models.DateTimeField()),
                ("verified_by_user_id", models.UUIDField(blank=True, null=True)),
                ("challenge_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "requests_contact_verification",
            },
        ),
        migrations.CreateModel(
            name="RequestMatch",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reasons",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16), size=None
                    ),
                ),
                ("detected_at", models.DateTimeField()),
            ],
            options={
                "db_table": "requests_match",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="property",
                        serialize=False,
                        to="requests.assistancerequest",
                    ),
                ),
                ("line1", models.CharField(max_length=200)),
                ("line2", models.CharField(blank=True, default="", max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("postal_code", models.CharField(max_length=10)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("single_family_home", "Single-family home"),
                            ("mobile_manufactured_home", "Mobile / manufactured home"),
                            ("townhome_condo", "Townhome / condominium"),
                            ("apartment", "Apartment"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "address_key",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
            ],
            options={
                "db_table": "requests_property",
            },
        ),
        migrations.CreateModel(
            name="Requester",
            fields=[
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="requester",
                        serialize=False,
                        to="requests.assistancerequest",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(max_length=32)),
                (
                    "email_key",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "phone_key",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "name_zip_key",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                ("anonymized_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "requests_requester",
            },
        ),
        migrations.AddIndex(
            model_name="assistancerequest",
            index=models.Index(
                fields=["status", "urgent_requested", "submitted_at"],
                name="req_status_urg_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assistancerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("urgency_justification", ""), ("urgent_requested", False)),
                    models.Q(
                        ("urgent_requested", True),
                        models.Q(("urgency_justification", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="req_urgency_justification_iff_urgent",
            ),
        ),
        migrations.AddConstraint(
            model_name="assistancerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closed_at__isnull", True),
                    models.Q(("status", "CANCELLED"), _negated=True),
                    ("closed_at__isnull", False),
                    _connector="OR",
                ),
                name="req_closed_at_when_terminal",
            ),
        ),
        migrations.AddField(
            model_name="requestcontactverification",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_verifications",
                to="requests.assistancerequest",
            ),
        ),
        migrations.AddField(
            model_name="requestmatch",
            name="prior_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matched_by",
                to="requests.assistancerequest",
            ),
        ),
        migrations.AddField(
            model_name="requestmatch",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="requests.assistancerequest",
            ),
        ),
        migrations.AddIndex(
            model_name="requestcontactverification",
            index=models.Index(fields=["request", "verified_at"], name="reqcv_request_idx"),
        ),
        migrations.AddConstraint(
            model_name="requestmatch",
            constraint=models.UniqueConstraint(
                fields=("request", "prior_request"), name="reqmatch_unique_pair"
            ),
        ),
    ]
