# Generated by Django 5.2.17 on 2026-09-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistancerequest",
            name="awaiting_approval_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assistancerequest",
            name="closed_by_user_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assistancerequest",
            name="contact_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="assistancerequest",
            name="need_category",
            field=models.CharField(
                choices=[
                    ("roof_or_ceiling", "Roof or ceiling"),
                    ("plumbing_or_water", "Plumbing or water"),
                    ("electrical", "Electrical"),
                    ("doors_windows_locks", "Doors, windows or locks"),
                    ("floors_or_stairs", "Floors or stairs"),
                    ("ramps_rails_grab_bars", "Ramps, rails or grab bars"),
                    ("painting_or_walls", "Painting or walls"),
                    ("yard_or_outside", "Yard or outside"),
                    ("something_else", "Something else or not sure"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="assistancerequest",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[("email", "Email"), ("phone_call", "Phone call")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("house", "House"),
                    ("townhouse", "Townhouse"),
                    ("apartment_or_condo", "Apartment or condo"),
                    ("mobile_or_manufactured_home", "Mobile or manufactured home"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
