# Generated by Django 5.2.17 on 2026-09-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0002_assistancerequest_awaiting_approval_at_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assistancerequest",
            name="req_urgency_justification_iff_urgent",
        ),
        migrations.AddField(
            model_name="assistancerequest",
            name="urgency_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("someone_could_get_hurt", "Someone could get hurt"),
                    (
                        "water_or_damage",
                        "Water is coming in or damage is getting worse",
                    ),
                    ("no_utilities", "No power, water, heat or cooling"),
                    ("cant_get_in_or_out", "Can't get in or out of the home safely"),
                    ("something_else", "Something else"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="assistancerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("urgency_justification", ""), ("urgent_requested", False)),
                    models.Q(
                        ("urgent_requested", True),
                        models.Q(
                            models.Q(("urgency_reason", "something_else"), _negated=True),
                            models.Q(("urgency_justification", ""), _negated=True),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="req_urgency_justification_iff_urgent",
            ),
        ),
        migrations.AddConstraint(
            model_name="assistancerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("urgency_reason", ""), ("urgent_requested", False)),
                    models.Q(
                        ("urgent_requested", True),
                        models.Q(("urgency_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="req_urgency_reason_iff_urgent",
            ),
        ),
    ]
