# Generated by Django 5.2.17 on 2026-09-29 00:37

import django.db.models.deletion
from django.db import migrations, models

import ham.platform.ids
import ham.requests.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "requests",
            "0003_remove_assistancerequest_req_urgency_justification_iff_urgent_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("initial", "Initial decision"),
                            ("reconsideration", "Reconsideration decision"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=16,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[("pastoral", "Pastoral"), ("board", "Board")],
                        max_length=16,
                    ),
                ),
                ("decided_by_user_id", models.UUIDField()),
                ("decided_at", models.DateTimeField()),
                ("effective_at", models.DateTimeField()),
                ("board_decided_on", models.DateField(blank=True, null=True)),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "family_or_others_can_help",
                                "Family or others may be able to help",
                            ),
                            (
                                "owner_or_landlord_responsible",
                                "The owner or landlord is responsible for this repair",
                            ),
                            (
                                "not_help_ham_offers",
                                "This isn't the kind of help HAM offers",
                            ),
                            ("couldnt_confirm", "We couldn't confirm what we needed"),
                            ("another_reason", "Another reason"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("approval_note", models.TextField(blank=True, default="")),
                ("urgent_approval", models.BooleanField(default=False)),
                ("took_over_from_user_id", models.UUIDField(blank=True, null=True)),
                ("unavailable_confirmed", models.BooleanField(default=False)),
                ("requester_phoned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requester_phoned_by_user_id",
                    models.UUIDField(blank=True, null=True),
                ),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                ("undone_by_user_id", models.UUIDField(blank=True, null=True)),
                ("effects_ran_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "requests_approval",
            },
            bases=(ham.requests.models.AppendOnlyOnceMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Reconsideration",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                (
                    "requested_via",
                    models.CharField(
                        choices=[("secure_page", "Secure page"), ("phone", "Phone")],
                        max_length=16,
                    ),
                ),
                ("recorded_by_user_id", models.UUIDField(blank=True, null=True)),
                ("requester_note", models.TextField(blank=True, default="")),
                (
                    "route",
                    models.CharField(
                        choices=[("pastoral", "Pastoral"), ("board", "Board")],
                        max_length=16,
                    ),
                ),
                ("original_decider_user_id", models.UUIDField()),
            ],
            options={
                "db_table": "requests_reconsideration",
            },
            bases=(ham.requests.models.AppendOnlyOnceMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RequestQuestion",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asked_by_user_id", models.UUIDField()),
                ("asked_at", models.DateTimeField()),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True, default="")),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "answered_via",
                    models.CharField(
                        blank=True,
                        choices=[("secure_page", "Secure page"), ("phone", "Phone")],
                        default="",
                        max_length=16,
                    ),
                ),
                ("answer_recorded_by_user_id", models.UUIDField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "close_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("withdrawn", "Withdrawn"),
                            ("request_closed", "Request closed"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("closed_by_user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "requests_question",
            },
            bases=(ham.requests.models.AppendOnlyOnceMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name="assistancerequest",
            name="req_closed_at_when_terminal",
        ),
        migrations.AddField(
            model_name="assistancerequest",
            name="reconsideration_deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assistancerequest",
            name="urgency_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assistancerequest",
            name="urgency_reviewed_by_user_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="assistancerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "CANCELLED"), _negated=True),
                    ("closed_at__isnull", False),
                    _connector="OR",
                ),
                name="req_closed_at_set_when_cancelled",
            ),
        ),
        migrations.AddConstraint(
            model_name="assistancerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "status__in",
                            [
                                "NEEDS_PHONE_CHECK",
                                "SUBMITTED",
                                "AWAITING_APPROVAL",
                                "RECONSIDERATION_PENDING",
                                "APPROVED",
                            ],
                        ),
                        _negated=True,
                    ),
                    ("closed_at__isnull", True),
                    _connector="OR",
                ),
                name="req_closed_at_null_while_open",
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="requests.assistancerequest",
            ),
        ),
        migrations.AddField(
            model_name="reconsideration",
            name="request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reconsideration",
                to="requests.assistancerequest",
            ),
        ),
        migrations.AddField(
            model_name="requestquestion",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="requests.assistancerequest",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(fields=["request", "decided_at"], name="approval_request_idx"),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.UniqueConstraint(
                condition=models.Q(("undone_at__isnull", True)),
                fields=("request", "stage"),
                name="approval_unique_live_stage",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("outcome", "rejected"), _negated=True),
                    models.Q(
                        models.Q(("reason_code", ""), _negated=True),
                        models.Q(("reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="approval_reason_required_when_rejected",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("stage", "reconsideration"), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="approval_reason_required_at_reconsideration",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("urgent_approval", True), _negated=True),
                    ("outcome", "approved"),
                    _connector="OR",
                ),
                name="approval_urgent_only_when_approved",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("route", "board"), _negated=True),
                    ("board_decided_on__isnull", False),
                    _connector="OR",
                ),
                name="approval_board_decided_on_required_for_board_route",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("took_over_from_user_id__isnull", True),
                    ("unavailable_confirmed", True),
                    _connector="OR",
                ),
                name="approval_takeover_requires_unavailable_confirmed",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("undone_at__isnull", True), ("undone_by_user_id__isnull", True)),
                    models.Q(
                        ("undone_at__isnull", False),
                        ("undone_by_user_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="approval_undone_fields_set_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("requester_phoned_at__isnull", True),
                        ("requester_phoned_by_user_id__isnull", True),
                    ),
                    models.Q(
                        ("requester_phoned_at__isnull", False),
                        ("requester_phoned_by_user_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="approval_phoned_fields_set_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="reconsideration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("requested_via", "phone"), _negated=True),
                    ("recorded_by_user_id__isnull", False),
                    _connector="OR",
                ),
                name="reconsideration_phone_requires_recorder",
            ),
        ),
        migrations.AddIndex(
            model_name="requestquestion",
            index=models.Index(
                condition=models.Q(("answered_at__isnull", True), ("closed_at__isnull", True)),
                fields=["request"],
                name="reqq_open_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="requestquestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("answer", ""), ("answered_at__isnull", True)),
                    models.Q(
                        models.Q(("answer", ""), _negated=True),
                        ("answered_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="reqq_answer_iff_answered_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="requestquestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("answered_at__isnull", False),
                    ("closed_at__isnull", False),
                    _negated=True,
                ),
                name="reqq_not_answered_and_closed",
            ),
        ),
    ]
