# Generated by Django 5.2.17 on 2026-09-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0004_approval_reconsideration_requestquestion_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="requestquestion",
            name="reqq_answer_iff_answered_at",
        ),
        migrations.AddConstraint(
            model_name="requestquestion",
            constraint=models.CheckConstraint(
                condition=models.Q(("answer", ""), ("answered_at__isnull", False), _connector="OR"),
                name="reqq_answer_requires_answered_at",
            ),
        ),
    ]
