# Generated by Django 5.2.17 on 2026-09-29 01:23

import django.db.models.deletion
from django.db import migrations, models

import ham.platform.ids
import ham.requests.models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0005_fix_reqq_answer_check"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrgencyReview",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("certify_urgency", "certify_urgency"),
                            ("decline_urgency", "decline_urgency"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "prior_urgency",
                    models.CharField(
                        choices=[
                            ("none", "none"),
                            ("awaiting_certification", "awaiting_certification"),
                            ("certified", "certified"),
                            ("not_certified", "not_certified"),
                        ],
                        max_length=24,
                    ),
                ),
                ("decided_by_user_id", models.UUIDField()),
                ("decided_at", models.DateTimeField()),
                ("effective_at", models.DateTimeField()),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                ("undone_by_user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "requests_urgency_review",
            },
            bases=(ham.requests.models.AppendOnlyOnceMixin, models.Model),
        ),
        migrations.AddField(
            model_name="approval",
            name="accompanying_urgency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("certify_urgency", "certify_urgency"),
                    ("decline_urgency", "decline_urgency"),
                ],
                max_length=24,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="prior_urgency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "none"),
                    ("awaiting_certification", "awaiting_certification"),
                    ("certified", "certified"),
                    ("not_certified", "not_certified"),
                ],
                max_length=24,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("accompanying_urgency__isnull", True),
                        ("prior_urgency__isnull", True),
                    ),
                    models.Q(
                        ("accompanying_urgency__isnull", False),
                        ("prior_urgency__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="approval_prior_urgency_fields_set_together",
            ),
        ),
        migrations.AddField(
            model_name="urgencyreview",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="urgency_reviews",
                to="requests.assistancerequest",
            ),
        ),
        migrations.AddIndex(
            model_name="urgencyreview",
            index=models.Index(fields=["request", "decided_at"], name="urgrev_request_idx"),
        ),
        migrations.AddConstraint(
            model_name="urgencyreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("undone_at__isnull", True), ("undone_by_user_id__isnull", True)),
                    models.Q(
                        ("undone_at__isnull", False),
                        ("undone_by_user_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="urgrev_undone_fields_set_together",
            ),
        ),
    ]
