# Generated by Django 5.2.17 on 2026-09-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0006_urgencyreview_approval_accompanying_urgency_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="approval",
            name="approval_takeover_requires_unavailable_confirmed",
        ),
        migrations.AddField(
            model_name="approval",
            name="took_over_basis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unavailable_ticked", "Marked unavailable"),
                    ("role_ended", "Original pastor's role ended"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="urgent_approval_emitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="urgencyreview",
            name="urgent_approval_emitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="requestquestion",
            name="close_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("withdrawn", "Withdrawn"),
                    ("request_closed", "Request closed"),
                    ("request_decided", "Request decided"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("took_over_from_user_id__isnull", True),
                    models.Q(("took_over_basis", ""), _negated=True),
                    _connector="OR",
                ),
                name="approval_takeover_requires_basis",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unavailable_confirmed", False),
                    ("took_over_basis", "unavailable_ticked"),
                    _connector="OR",
                ),
                name="approval_unavailable_confirmed_matches_basis",
            ),
        ),
    ]
