# Generated by Django 5.2.17 on 2026-09-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0007_fix3a_undo_and_takeover_facts"),
    ]

    operations = [
        migrations.AddField(
            model_name="approval",
            name="banner_cleared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="urgencyreview",
            name="banner_cleared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="urgencyreview",
            name="prior_status",
            field=models.CharField(
                choices=[
                    ("NEEDS_PHONE_CHECK", "NEEDS_PHONE_CHECK"),
                    ("SUBMITTED", "SUBMITTED"),
                    ("AWAITING_APPROVAL", "AWAITING_APPROVAL"),
                    ("CANCELLED", "CANCELLED"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("RECONSIDERATION_PENDING", "RECONSIDERATION_PENDING"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
