# Generated by Django 5.2.17 on 2026-09-28 13:05

import django.db.models.deletion
from django.db import migrations, models

import ham.platform.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestMediaBatch",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("initial", "Initial"), ("reopened", "Reopened")],
                        max_length=16,
                    ),
                ),
                ("opened_by_user_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("max_photos", models.PositiveIntegerField()),
                ("max_videos", models.PositiveIntegerField()),
                ("max_video_seconds", models.PositiveIntegerField()),
                ("rules_version", models.CharField(max_length=32)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_batches",
                        to="requests.assistancerequest",
                    ),
                ),
            ],
            options={
                "db_table": "media_request_batch",
                "ordering": ("request_id", "number"),
            },
        ),
        migrations.CreateModel(
            name="RequestMedia",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_kind",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")], max_length=8
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("rejected", "Rejected"),
                            ("removed", "Removed"),
                            ("purged", "Purged"),
                        ],
                        default="reserved",
                        max_length=16,
                    ),
                ),
                (
                    "quarantine_key",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "storage_key",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("thumb_key", models.CharField(blank=True, default="", max_length=200)),
                (
                    "detected_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("too_long", "Too long"),
                            ("too_large", "Too large"),
                            ("unsupported", "Unsupported"),
                            ("corrupt", "Corrupt"),
                            ("processing_unavailable", "Processing unavailable"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "uploaded_by_type",
                    models.CharField(
                        choices=[("requester", "Requester"), ("user", "User")],
                        max_length=16,
                    ),
                ),
                ("uploaded_by_user_id", models.UUIDField(blank=True, null=True)),
                ("reserved_at", models.DateTimeField()),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="requests.assistancerequest",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ham_media.requestmediabatch",
                    ),
                ),
            ],
            options={
                "db_table": "media_request_item",
                "ordering": ("reserved_at",),
            },
        ),
        migrations.AddIndex(
            model_name="requestmediabatch",
            index=models.Index(fields=["request", "closed_at"], name="media_batch_open_idx"),
        ),
        migrations.AddConstraint(
            model_name="requestmediabatch",
            constraint=models.UniqueConstraint(
                fields=("request", "number"), name="media_batch_unique_number"
            ),
        ),
        migrations.AddIndex(
            model_name="requestmedia",
            index=models.Index(fields=["batch", "status"], name="media_item_batch_status_idx"),
        ),
        migrations.AddIndex(
            model_name="requestmedia",
            index=models.Index(fields=["request", "status"], name="media_item_request_status_idx"),
        ),
    ]
