# Generated by Django 5.2.17 on 2026-09-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ham_media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestmedia",
            name="failure_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("too_long", "Too long"),
                    ("too_large", "Too large"),
                    ("unsupported", "Unsupported"),
                    ("corrupt", "Corrupt"),
                    ("processing_unavailable", "Processing unavailable"),
                    ("upload_expired", "Upload expired"),
                    ("processing_timed_out", "Processing timed out"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
