# Generated by Django 5.2.17 on 2026-09-28 00:01
# Hand-edited: added the `citext` extension (foundation.md §3 "email (citext, unique, **S**)")
# as the first operation, ahead of the generated CreateModel calls.

import django.contrib.postgres.operations
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ham.identity.models
import ham.platform.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # citext gives case-insensitive uniqueness/lookups on User.email without normalizing
        # case in application code everywhere (foundation.md §3).
        django.contrib.postgres.operations.CreateExtension("citext"),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    ham.identity.models.CIEmailField(max_length=254, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("first_sign_in_at", models.DateTimeField(blank=True, null=True)),
                ("last_sign_in_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_by_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "identity_user",
            },
            managers=[
                ("objects", ham.identity.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="SharedIdentityProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "mobile_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("notify_email", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "identity_profile",
            },
        ),
        migrations.CreateModel(
            name="ImpersonationSession",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("started_at", models.DateTimeField()),
                ("last_activity_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Manual"),
                            ("idle_timeout", "Idle timeout"),
                            ("signed_out", "Signed out"),
                            ("target_disabled", "Target disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impersonations_started",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impersonations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "identity_impersonation",
                "indexes": [
                    models.Index(
                        fields=["admin_user", "ended_at"],
                        name="impersonation_admin_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATOR", "Administrator"),
                            ("ASSISTANT_DIRECTOR", "Assistant Director"),
                            ("BOARD_REPRESENTATIVE", "Board representative"),
                            ("CONTRACTOR", "Contractor"),
                            ("HAM_DIRECTOR", "HAM Director"),
                            ("PASTOR", "Pastor"),
                            ("PROJECT_LEADER", "Project Leader"),
                            ("SOCIAL_MEDIA_SPECIALIST", "Social Media Specialist"),
                            ("TASK_LEADER", "Task Leader"),
                            ("VOLUNTEER", "Volunteer"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        blank=True,
                        choices=[("project", "Project"), ("task", "Task")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("scope_id", models.UUIDField(blank=True, null=True)),
                ("granted_by_id", models.UUIDField(blank=True, null=True)),
                ("granted_at", models.DateTimeField()),
                (
                    "grant_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "revoke_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "identity_role_assignment",
                "indexes": [
                    models.Index(fields=["user", "role"], name="role_assignment_user_role_idx"),
                    models.Index(
                        fields=["scope_type", "scope_id"],
                        name="role_assignment_scope_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "role__in",
                                    [
                                        "ADMINISTRATOR",
                                        "ASSISTANT_DIRECTOR",
                                        "BOARD_REPRESENTATIVE",
                                        "CONTRACTOR",
                                        "HAM_DIRECTOR",
                                        "PASTOR",
                                        "SOCIAL_MEDIA_SPECIALIST",
                                        "VOLUNTEER",
                                    ],
                                ),
                                ("scope_type__isnull", True),
                                ("scope_id__isnull", True),
                            ),
                            models.Q(
                                ("role", "PROJECT_LEADER"),
                                ("scope_type", "project"),
                                ("scope_id__isnull", False),
                            ),
                            models.Q(
                                ("role", "TASK_LEADER"),
                                ("scope_type", "task"),
                                ("scope_id__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="role_scope_kind_matches",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("revoked_at__isnull", True), ("scope_type__isnull", True)
                        ),
                        fields=("user", "role"),
                        name="uniq_active_global_role_per_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("revoked_at__isnull", True), ("scope_type__isnull", False)
                        ),
                        fields=("role", "scope_type", "scope_id"),
                        name="uniq_active_leader_per_scope",
                    ),
                ],
            },
        ),
    ]
