# Generated by Django 5.2.17 on 2026-09-28 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ham.identity.models
import ham.platform.ids


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="totp_device",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("secret_encrypted", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "identity_totp_device",
            },
        ),
        migrations.CreateModel(
            name="SignInChallenge",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", ham.identity.models.CIEmailField(max_length=254)),
                ("code_hash", models.CharField(max_length=64)),
                ("link_token_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("next_url", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "db_table": "identity_sign_in_challenge",
                "indexes": [
                    models.Index(
                        fields=["email", "created_at"],
                        name="sign_in_challenge_email_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "identity_recovery_code",
                "indexes": [
                    models.Index(fields=["user", "used_at"], name="recovery_code_user_used_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "identity_trusted_device",
                "indexes": [models.Index(fields=["user"], name="trusted_device_user_idx")],
            },
        ),
    ]
