# Generated by Django 5.2.17 on 2026-09-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_totpdevice_signinchallenge_recoverycode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invitation_resent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
