# Generated by Django 5.2.17 on 2026-09-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0004_user_invitation_resent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="signinchallenge",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="signinchallenge",
            index=models.Index(
                fields=["ip_address", "created_at"], name="sign_in_challenge_ip_idx"
            ),
        ),
    ]
