# Generated by Django 5.2.17 on 2026-09-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0005_signinchallenge_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impersonationsession",
            name="end_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual"),
                    ("idle_timeout", "Idle timeout"),
                    ("signed_out", "Signed out"),
                    ("target_disabled", "Target disabled"),
                    ("session_expired", "Session expired"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
