# Generated by Django 5.2.17 on 2026-09-28 13:00

from django.db import migrations, models

import ham.platform.clock
import ham.platform.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_user_id", models.UUIDField()),
                ("outbox_event_id", models.UUIDField(blank=True, null=True)),
                ("kind", models.CharField(max_length=100)),
                ("subject_type", models.CharField(max_length=50)),
                ("subject_id", models.UUIDField()),
                ("title", models.CharField(max_length=200)),
                ("urgent", models.BooleanField(default=False)),
                ("requires_ack", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=ham.platform.clock.now)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_user_id", "created_at"],
                        name="notif_recipient_created_idx",
                    ),
                    models.Index(
                        fields=["recipient_user_id", "read_at"],
                        name="notif_recipient_unread_idx",
                    ),
                    models.Index(
                        fields=["recipient_user_id", "requires_ack", "acknowledged_at"],
                        name="notif_recipient_ack_idx",
                    ),
                ],
            },
        ),
    ]
