# Generated by Django 5.2.17 on 2026-09-28 12:58

from django.db import migrations, models

import ham.platform.models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchprofile",
            name="serves_days",
            field=models.JSONField(default=ham.platform.models.default_serves_days),
        ),
    ]
