# Generated by Django 5.2.17 on 2026-09-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0002_churchprofile_serves_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchprofile",
            name="state",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
