# Generated by Django 5.2.17 on 2026-09-27 23:57

import django.db.models.deletion
from django.db import migrations, models

import ham.platform.clock
import ham.platform.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("seq", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "id",
                    models.UUIDField(default=ham.platform.ids.uuid7, editable=False, unique=True),
                ),
                ("event_type", models.CharField(max_length=200)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("occurred_at", models.DateTimeField(default=ham.platform.clock.now)),
                ("aggregate_type", models.CharField(max_length=100)),
                ("aggregate_id", models.UUIDField()),
                ("payload", models.JSONField(default=dict)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "outbox_event",
                "ordering": ["seq"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "occurred_at"],
                        name="outbox_event_type_time_idx",
                    ),
                    models.Index(
                        fields=["aggregate_type", "aggregate_id"],
                        name="outbox_event_agg_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxDelivery",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subscriber", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("dead", "Dead-lettered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="outbox.outboxevent",
                        to_field="id",
                    ),
                ),
            ],
            options={
                "db_table": "outbox_delivery",
                "indexes": [
                    models.Index(
                        fields=["subscriber", "status"],
                        name="outbox_delivery_sub_status_idx",
                    ),
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="outbox_delivery_due_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "subscriber"),
                        name="uniq_outbox_delivery_event_subscriber",
                    )
                ],
            },
        ),
    ]
