# Generated by Django 5.2.17 on 2026-09-28 13:07

from django.db import migrations, models

import ham.platform.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntakeSource",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("created_by_user_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_by_user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "requester_portal_intake_source",
            },
        ),
        migrations.CreateModel(
            name="IntakeDraft",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payload_ciphertext", models.TextField()),
                ("email_key", models.CharField(blank=True, default="", max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("request_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "requester_portal_draft",
                "indexes": [
                    models.Index(fields=["expires_at"], name="rp_draft_expires_idx"),
                    models.Index(fields=["email_key", "created_at"], name="rp_draft_email_idx"),
                    models.Index(fields=["ip_address", "created_at"], name="rp_draft_ip_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RequesterAccessLink",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("token_ciphertext", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("regenerated", "Regenerated"),
                        ],
                        max_length=16,
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoke_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("superseded", "Superseded"),
                            ("anonymized", "Anonymized"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("verification_id", models.UUIDField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "requester_portal_link",
                "indexes": [models.Index(fields=["request_id"], name="rp_link_request_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("request_id",),
                        name="rp_link_one_live_per_request",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RequesterVerificationChallenge",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("intake", "Intake"),
                            ("link_regeneration", "Link regeneration"),
                        ],
                        max_length=32,
                    ),
                ),
                ("draft_id", models.UUIDField(blank=True, null=True)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("email_key", models.CharField(max_length=64)),
                ("code_hash", models.CharField(max_length=64)),
                ("link_token_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "requester_portal_challenge",
                "indexes": [
                    models.Index(
                        fields=["email_key", "created_at"],
                        name="rp_challenge_email_idx",
                    ),
                    models.Index(fields=["ip_address", "created_at"], name="rp_challenge_ip_idx"),
                    models.Index(fields=["expires_at"], name="rp_challenge_expires_idx"),
                    models.Index(fields=["draft_id"], name="rp_challenge_draft_idx"),
                    models.Index(fields=["request_id"], name="rp_challenge_request_idx"),
                ],
            },
        ),
    ]
