# Generated by Django 5.2.17 on 2026-09-28 17:45

from django.db import migrations, models

import ham.platform.ids


class Migration(migrations.Migration):
    dependencies = [
        ("requester_portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FindRequestAttempt",
            fields=[
                (
                    "id",
                    ham.platform.ids.UUID7Field(
                        default=ham.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "requester_portal_find_attempt",
                "indexes": [
                    models.Index(fields=["ip_address", "created_at"], name="rp_find_ip_idx")
                ],
            },
        ),
    ]
