# Generated by Django 5.2.17 on 2026-09-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requester_portal", "0002_findrequestattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requesterverificationchallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("intake", "Intake"),
                    ("link_regeneration", "Link regeneration"),
                    ("find", "Find my request"),
                ],
                max_length=32,
            ),
        ),
    ]
